services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: --wait_timeout=28800 --interactive_timeout=28800
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1g"

  server:
    build: .
    environment:
      - CERT_PASSKEY=${CERT_PASSKEY}
      - FLASK_APP=app.py
      - FLASK_ENV=development
    # command: flask run --host=0.0.0.0 --port=80
    volumes:
      - .:/app
      - ./logs:/logs
    ports:
      - "443:443"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:443/test"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
    driver: local
