services:
  server:
    build: .
    command: >
      uvicorn server:app
      --host 0.0.0.0
      --port 443
      --ssl-keyfile /secrets/key.pem
      --ssl-certfile /secrets/cert.pem
    environment:
      ENVIRONMENT: prod
      LOCAL_TIMEZONE: America/New_York
      CERT_PASSKEY: ${CERT_PASSKEY}
      MYSQL_USER_PASSWORD_FILE: /run/secrets/mysql_user_password
      TESTDB_USER_PASSWORD_FILE: /run/secrets/testdb_user_password
      DATABASE_URL: mysql+aiomysql://user@db/lurkerbothunterdb
      DATABASE_PREFIX: mysql+aiomysql://
      DATABASE_NAME: lurkerbothunterdb
      DB_SERVICE_NAME: db
      DB_PORT: 3306
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_DB_INDEX: 0
    volumes:
      - .:/server
      - ./logs/server.log:/logs/server.log
      - ./logs/db.log:/logs/db.log
    ports:
      - "443:443"
    secrets:
      - mysql_user_password
      - testdb_user_password
    depends_on:
      db:
        condition: service_healthy
      test-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:443/test"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: lurkerbothunterdb
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
    ports:
      - "3306:3306"
    secrets:
      - mysql_root_password
      - mysql_user_password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: --wait_timeout=28800 --interactive_timeout=28800
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1g"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  test-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: lurkerbothunter-testdb
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/testdb_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/testdb_user_password
    ports:
      - "3307:3306"
    secrets:
      - testdb_root_password
      - testdb_user_password
    volumes:
      - testdb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: --wait_timeout=28800 --interactive_timeout=28800
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1g"

  test-redis:
    image: redis:latest
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
    driver: local
  testdb_data:
    driver: local

secrets:
  mysql_root_password:
    file: ./secrets/.mysql_root_password.txt
  mysql_user_password:
    file: ./secrets/.mysql_user_password.txt
  testdb_root_password:
    file: ./secrets/.testdb_root_password.txt
  testdb_user_password:
    file: ./secrets/.testdb_user_password.txt
