services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: lurkerbothunterdb
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
    ports:
      - "3306:3306"
    secrets:
      - mysql_root_password
      - mysql_user_password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: --wait_timeout=28800 --interactive_timeout=28800
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1g"

  server:
    build: .
    environment:
      CERT_PASSKEY: ${CERT_PASSKEY}
      MYSQL_USER_PASSWORD_FILE: /run/secrets/mysql_user_password
      DATABASE_URL: mysql+aiomysql://user@db/lurkerbothunterdb
    volumes:
      - .:/server
      - ./logs:/logs
    ports:
      - "443:443"
    secrets:
      - mysql_user_password
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:443/test"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
    driver: local

secrets:
  mysql_root_password:
    file: ./secrets/.mysql_root_password
  mysql_user_password:
    file: ./secrets/.mysql_user_password
